import type { Metadata } from 'next'
import './globals.css'
import Providers from '@/lib/Providers'
import { Poppins } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '800'],
  subsets: ['latin'],
  variable: '--font-poppins',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`antialiased	  ${poppins.className}`}>
        <Providers>
          <section className="lg:scale-100 md:scale-75 scale-50">
            {children}
          </section>
        </Providers>
      </body>
    </html>
  )
}
